GET http://localhost:3000/

###

GET http://localhost:3000/api/heros/a26ab13a-266e-425f-b3c3-35bd32fccdca

###
GET http://localhost:3000/api/heros

###

POST http://localhost:3000/api/heros
Content-Type: application/json

{
    
    "name": "Spider-Man",
    "power": 5,
    "speed": 5
}

###

DELETE http://localhost:3000/api/heros/36702312-16a9-419c-baf7-a85169ecbe23

###

PUT http://localhost:3000/api/heros/a26ab13a-266e-425f-b3c3-35bd32fccdca
Content-Type: application/json

{
    "name": "he-man",
    "power": 5,
    "speed": 1
}
