GET http://localhost:3000/

###

GET http://localhost:3000/api/heros/4

###
GET http://localhost:3000/api/heros

###

POST http://localhost:3000/api/heros
Content-Type: application/json

{
    
    "name": "Spider-Man",
    "power": 2,
    "speed": 5
}

###

DELETE http://localhost:3000/api/heros/2

###

PUT http://localhost:3000/api/heros/1
Content-Type: application/json

{
    "name": "batman",
    "power": 3,
    "speed": 1
}
